### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by domh** [ennerperez/msbuild-confuserex#1]
Apologies if this is a Newbie question.  Does this project enable you to call confuserEx using MSBuild targets in a csproj file?  If so could you advise me on installation and usage please, it could, if it is, be a complete saviour!

Many thanks for any help.

Dom

**Comment by ennerperez** [comment]
Yes, only add as nuget to you proyect them it will create a Confuser.crproj in project, check Test project for more information.
